"""Tests for the self-contained HTML assessment report generator."""

from __future__ import annotations

import html

from retrace.core.pipeline import AnalysisResult, Component, Trace
from retrace.export.html_report import generate_html_report, save_html_report

# ── Fixtures ─────────────────────────────────────────────────────────────


def _empty_result() -> AnalysisResult:
    return AnalysisResult(image_path="empty_board.jpg")


def _basic_result() -> AnalysisResult:
    return AnalysisResult(
        image_path="test_board.jpg",
        pipeline_version="0.3.0",
        timestamp="2024-06-15T12:00:00Z",
        components=[
            Component(
                id="C0001",
                label="ic",
                confidence=0.95,
                bbox=(10, 20, 50, 30),
                marking="STM32F4",
                part_number="STM32F407VGT6",
                datasheet_url="https://st.com/stm32f407.pdf",
                value="",
                package="LQFP-100",
            ),
            Component(
                id="C0002",
                label="capacitor",
                confidence=0.80,
                bbox=(100, 200, 10, 10),
                marking="",
                value="100nF",
                package="0402",
            ),
            Component(
                id="C0003",
                label="resistor",
                confidence=0.55,
                bbox=(150, 200, 8, 8),
                marking="103",
                value="10k",
                package="0402",
            ),
        ],
        traces=[
            Trace(
                id="T001",
                points=[(10, 20), (100, 200)],
                width_px=2.0,
                from_component="C0001",
                to_component="C0002",
            ),
        ],
    )


def _security_result() -> AnalysisResult:
    """Result with components that trigger security findings."""
    return AnalysisResult(
        image_path="security_board.jpg",
        components=[
            Component(
                id="J1",
                label="header",
                confidence=0.9,
                bbox=(10, 10, 40, 10),
                marking="JTAG",
            ),
            Component(
                id="J2",
                label="connector",
                confidence=0.85,
                bbox=(50, 50, 30, 10),
                marking="UART DEBUG",
            ),
            Component(
                id="U1",
                label="ic",
                confidence=0.75,
                bbox=(100, 100, 60, 40),
                marking="SWD CONNECTOR",
            ),
        ],
    )


# ── Tests ────────────────────────────────────────────────────────────────


class TestEmptyResult:
    def test_produces_valid_html(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert report.startswith("<!DOCTYPE html>")
        assert "</html>" in report

    def test_contains_all_sections(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert "Executive Summary" in report
        assert "Security Findings" in report
        assert "Component Inventory" in report
        assert "Trace Analysis" in report

    def test_no_findings_message(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert "No exposed debug interfaces detected." in report


class TestBasicReport:
    def test_title_appears(self):
        result = _basic_result()
        report = generate_html_report(result, title="My Custom Board")
        assert "My Custom Board" in report

    def test_title_in_html_title_tag(self):
        result = _basic_result()
        report = generate_html_report(result, title="PCB-42")
        assert "<title>re:trace — PCB-42</title>" in report

    def test_header_section(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "re:trace — Hardware Security Assessment" in report
        assert "Pipeline v0.3.0" in report

    def test_component_count_in_stats(self):
        result = _basic_result()
        report = generate_html_report(result)
        # 3 components
        assert ">3<" in report

    def test_identified_count_in_stats(self):
        result = _basic_result()
        report = generate_html_report(result)
        # 1 identified (STM32F407VGT6)
        assert ">1<" in report

    def test_footer(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "Generated by re:trace" in report
        assert "github.com/ericrihm/retrace" in report


class TestHTMLEscaping:
    def test_component_marking_escaped(self):
        result = AnalysisResult(
            image_path="test.jpg",
            components=[
                Component(
                    id="X1",
                    label="ic",
                    confidence=0.9,
                    bbox=(0, 0, 10, 10),
                    marking='<script>alert("xss")</script>',
                ),
            ],
        )
        report = generate_html_report(result)
        # The raw script tag must NOT appear
        assert '<script>alert("xss")</script>' not in report
        # The escaped version must appear
        assert html.escape('<script>alert("xss")</script>') in report

    def test_xss_in_part_number_escaped(self):
        result = AnalysisResult(
            image_path="test.jpg",
            components=[
                Component(
                    id="X2",
                    label="ic",
                    confidence=0.8,
                    bbox=(0, 0, 10, 10),
                    part_number='<img src=x onerror=alert(1)>',
                ),
            ],
        )
        report = generate_html_report(result)
        assert "<img src=x" not in report
        assert html.escape('<img src=x onerror=alert(1)>') in report

    def test_xss_in_title_escaped(self):
        report = generate_html_report(
            _empty_result(),
            title='<script>alert("t")</script>',
        )
        # Must not contain unescaped script
        assert '<script>alert("t")</script>' not in report


class TestDatasheetURLs:
    def test_valid_https_url_becomes_link(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert 'href="https://st.com/stm32f407.pdf"' in report

    def test_javascript_url_rejected(self):
        result = AnalysisResult(
            image_path="test.jpg",
            components=[
                Component(
                    id="X3",
                    label="ic",
                    confidence=0.9,
                    bbox=(0, 0, 10, 10),
                    part_number="EVIL-IC",
                    datasheet_url='javascript:alert("xss")',
                ),
            ],
        )
        report = generate_html_report(result)
        assert "javascript:" not in report
        # Part number should still appear but not as link
        assert "EVIL-IC" in report

    def test_http_url_allowed(self):
        result = AnalysisResult(
            image_path="test.jpg",
            components=[
                Component(
                    id="X4",
                    label="ic",
                    confidence=0.9,
                    bbox=(0, 0, 10, 10),
                    part_number="GOOD-IC",
                    datasheet_url="http://example.com/datasheet.pdf",
                ),
            ],
        )
        report = generate_html_report(result)
        assert 'href="http://example.com/datasheet.pdf"' in report

    def test_data_url_rejected(self):
        result = AnalysisResult(
            image_path="test.jpg",
            components=[
                Component(
                    id="X5",
                    label="ic",
                    confidence=0.9,
                    bbox=(0, 0, 10, 10),
                    part_number="DATA-IC",
                    datasheet_url="data:text/html,<h1>pwned</h1>",
                ),
            ],
        )
        report = generate_html_report(result)
        assert "data:text/html" not in report


class TestSecurityFindings:
    def test_jtag_detected(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "JTAG" in report
        assert "HIGH" in report

    def test_uart_detected(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "UART" in report
        assert "MEDIUM" in report

    def test_swd_detected(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "SWD" in report

    def test_cwe_hyperlinked(self):
        result = _security_result()
        report = generate_html_report(result)
        assert 'href="https://cwe.mitre.org/data/definitions/1191.html"' in report
        assert 'href="https://cwe.mitre.org/data/definitions/1299.html"' in report

    def test_cwe_text_present(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "CWE-1191" in report
        assert "CWE-1299" in report

    def test_severity_badges(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "badge-high" in report
        assert "badge-medium" in report

    def test_no_findings_with_clean_board(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "No exposed debug interfaces detected." in report

    def test_finding_count_in_exec_summary(self):
        result = _security_result()
        report = generate_html_report(result)
        assert "debug interface" in report.lower()
        assert "requiring physical access controls" in report


class TestConfidenceBars:
    def test_high_confidence_green(self):
        result = _basic_result()
        report = generate_html_report(result)
        # STM32F4 has 0.95 confidence — should be green
        assert "#22c55e" in report

    def test_medium_confidence_yellow(self):
        result = _basic_result()
        report = generate_html_report(result)
        # Capacitor has 0.80 confidence — should be yellow
        assert "#f59e0b" in report

    def test_low_confidence_red(self):
        result = _basic_result()
        report = generate_html_report(result)
        # Resistor has 0.55 confidence — should be red
        assert "#ef4444" in report

    def test_confidence_bar_rendered(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "conf-bar" in report
        assert "conf-bar-fill" in report


class TestZones:
    def test_zones_rendered_when_provided(self):
        result = _basic_result()
        zones = [
            ("CPU Core", "cpu", ["C0001"]),
            ("Power Rail", "power", ["C0002", "C0003"]),
        ]
        report = generate_html_report(result, zones=zones)
        assert "Functional Zones" in report
        assert "CPU Core" in report
        assert "Power Rail" in report

    def test_zone_component_count(self):
        result = _basic_result()
        zones = [("IO Block", "io", ["C0001", "C0002", "C0003"])]
        report = generate_html_report(result, zones=zones)
        assert "3 components" in report

    def test_zones_not_rendered_when_none(self):
        result = _basic_result()
        report = generate_html_report(result, zones=None)
        assert "Functional Zones" not in report

    def test_zone_names_escaped(self):
        result = _basic_result()
        zones = [('<script>Zone', "cpu", ["C0001"])]
        report = generate_html_report(result, zones=zones)
        assert "<script>Zone" not in report
        assert html.escape("<script>Zone") in report


class TestTraceAnalysis:
    def test_trace_count(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "1 trace" in report

    def test_no_traces_message(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert "No traces detected." in report


class TestTableSorting:
    def test_sortable_columns_have_attribute(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert 'data-sortable' in report

    def test_sort_js_included(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "data-sort-dir" in report
        assert "localeCompare" in report

    def test_no_eval_in_js(self):
        result = _basic_result()
        report = generate_html_report(result)
        # Extract script content
        assert "eval(" not in report

    def test_no_innerhtml_for_data_in_js(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "innerHTML" not in report


class TestTypeBadges:
    def test_type_badges_have_colors(self):
        result = _basic_result()
        report = generate_html_report(result)
        # IC red
        assert "239,68,68" in report  # #ef4444
        # Capacitor blue
        assert "59,130,246" in report  # #3b82f6
        # Resistor green
        assert "34,197,94" in report  # #22c55e


class TestPrintStyles:
    def test_print_media_query(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "@media print" in report


# ── Additional coverage tests ─────────────────────────────────────────────

class TestClassifyNet:
    """Tests for _classify_net net-type classification branches."""

    def _make_trace(self, from_id, to_id, width_px=2.0):
        return Trace(
            id="T_test",
            points=[(0, 0), (10, 10)],
            from_component=from_id,
            to_component=to_id,
            width_px=width_px,
        )

    def test_debug_net_via_jtag_marking(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "J1": Component(id="J1", label="header", confidence=0.9, bbox=(0, 0, 10, 10), marking="JTAG"),
            "U1": Component(id="U1", label="ic", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("J1", "U1")
        assert _classify_net(trace, comp_map) == "debug"

    def test_power_net_via_vcc_marking(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "U1": Component(id="U1", label="ic", confidence=0.9, bbox=(0, 0, 10, 10), marking="VCC"),
            "C1": Component(id="C1", label="capacitor", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("U1", "C1")
        assert _classify_net(trace, comp_map) == "power"

    def test_power_net_via_wide_trace(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "R1": Component(id="R1", label="resistor", confidence=0.9, bbox=(0, 0, 10, 10)),
            "R2": Component(id="R2", label="resistor", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("R1", "R2", width_px=6.0)
        assert _classify_net(trace, comp_map) == "power"

    def test_clock_net(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "X1": Component(id="X1", label="crystal", confidence=0.9, bbox=(0, 0, 10, 10), marking="XTAL"),
            "U1": Component(id="U1", label="ic", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("X1", "U1")
        assert _classify_net(trace, comp_map) == "clock"

    def test_ground_net(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "GND": Component(id="GND", label="test_point", confidence=0.9, bbox=(0, 0, 5, 5), marking="GND"),
            "R1": Component(id="R1", label="resistor", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("GND", "R1")
        assert _classify_net(trace, comp_map) == "ground"

    def test_data_net(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "U1": Component(id="U1", label="ic", confidence=0.9, bbox=(0, 0, 10, 10), marking="MOSI"),
            "U2": Component(id="U2", label="ic", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("U1", "U2")
        assert _classify_net(trace, comp_map) == "data"

    def test_signal_net_fallback(self):
        from retrace.export.html_report import _classify_net
        comp_map = {
            "R1": Component(id="R1", label="resistor", confidence=0.9, bbox=(0, 0, 10, 10)),
            "R2": Component(id="R2", label="resistor", confidence=0.9, bbox=(20, 20, 10, 10)),
        }
        trace = self._make_trace("R1", "R2", width_px=1.0)
        assert _classify_net(trace, comp_map) == "signal"

    def test_unknown_component_refs(self):
        from retrace.export.html_report import _classify_net
        comp_map: dict = {}
        trace = self._make_trace("MISSING_A", "MISSING_B")
        # Should not raise; falls back to "signal"
        net = _classify_net(trace, comp_map)
        assert net in ("signal", "power", "debug", "clock", "ground", "data")


class TestCvssGaugeSvg:
    def test_no_score_returns_empty(self):
        from retrace.export.html_report import _cvss_gauge_svg
        assert _cvss_gauge_svg(0) == ""
        assert _cvss_gauge_svg(0.0) == ""

    def test_high_score_red(self):
        from retrace.export.html_report import _cvss_gauge_svg
        svg = _cvss_gauge_svg(8.5)
        assert "#ef4444" in svg  # high severity red

    def test_medium_score_yellow(self):
        from retrace.export.html_report import _cvss_gauge_svg
        svg = _cvss_gauge_svg(5.5)
        assert "#f59e0b" in svg  # medium yellow

    def test_low_score_blue(self):
        from retrace.export.html_report import _cvss_gauge_svg
        svg = _cvss_gauge_svg(2.5)
        assert "#3b82f6" in svg  # low blue


class TestAttackChainSvg:
    def test_empty_returns_empty_string(self):
        from retrace.export.html_report import _attack_chain_svg
        assert _attack_chain_svg([]) == ""

    def test_single_path_renders_svg(self):
        from retrace.export.html_report import _attack_chain_svg
        paths = [("JTAG", "MCU", "Physical access")]
        svg = _attack_chain_svg(paths)
        assert svg.startswith("<svg")
        assert "</svg>" in svg
        assert "JTAG" in svg
        assert "MCU" in svg

    def test_multiple_paths(self):
        from retrace.export.html_report import _attack_chain_svg
        paths = [
            ("JTAG", "MCU", "Step 1"),
            ("UART", "CPU", "Step 2"),
        ]
        svg = _attack_chain_svg(paths)
        assert "JTAG" in svg
        assert "UART" in svg
        assert svg.count("<rect") >= 4  # 2 rects per path


class TestAttackPathsInReport:
    def test_attack_paths_section_rendered(self):
        result = _basic_result()
        paths = [("JTAG", "MCU", "Physical JTAG access")]
        report = generate_html_report(result, attack_paths=paths)
        assert "Attack Chains" in report
        assert "JTAG" in report

    def test_no_attack_paths_no_section(self):
        result = _basic_result()
        report = generate_html_report(result, attack_paths=None)
        assert "Attack Chains" not in report

    def test_empty_attack_paths_no_section(self):
        result = _basic_result()
        report = generate_html_report(result, attack_paths=[])
        assert "Attack Chains" not in report


class TestRiskMatrixSvg:
    def test_empty_findings_returns_empty(self):
        from retrace.export.html_report import _risk_matrix_svg
        # No findings → no parts → empty string
        assert _risk_matrix_svg([]) == ""

    def test_single_high_finding(self):
        from retrace.export.html_report import _risk_matrix_svg
        findings = [{"severity": "HIGH"}]
        bar = _risk_matrix_svg(findings)
        assert "risk-bar" in bar
        assert "#ef4444" in bar

    def test_mixed_severities(self):
        from retrace.export.html_report import _risk_matrix_svg
        findings = [
            {"severity": "HIGH"},
            {"severity": "MEDIUM"},
            {"severity": "LOW"},
        ]
        bar = _risk_matrix_svg(findings)
        assert "#ef4444" in bar
        assert "#f59e0b" in bar
        assert "#3b82f6" in bar


class TestTraceNetBreakdown:
    """Tests for net-type breakdown in trace analysis section."""

    def test_net_breakdown_shows_debug_net(self):
        result = AnalysisResult(
            image_path="trace_test.jpg",
            components=[
                Component(id="J1", label="header", confidence=0.9,
                          bbox=(0, 0, 10, 10), marking="JTAG"),
                Component(id="U1", label="ic", confidence=0.9,
                          bbox=(20, 20, 10, 10)),
            ],
            traces=[
                Trace(id="T1", points=[(0, 0), (20, 20)],
                      from_component="J1", to_component="U1", width_px=2.0),
            ],
        )
        report = generate_html_report(result)
        assert "debug" in report

    def test_net_breakdown_shows_power_net(self):
        result = AnalysisResult(
            image_path="trace_test.jpg",
            components=[
                Component(id="U1", label="ic", confidence=0.9,
                          bbox=(0, 0, 10, 10), marking="VCC"),
                Component(id="C1", label="capacitor", confidence=0.9,
                          bbox=(20, 20, 5, 5)),
            ],
            traces=[
                Trace(id="T1", points=[(0, 0), (20, 20)],
                      from_component="U1", to_component="C1", width_px=2.0),
            ],
        )
        report = generate_html_report(result)
        assert "power" in report


class TestSaveHtmlReport:
    def test_save_creates_file(self, tmp_path):
        result = _basic_result()
        out = tmp_path / "report.html"
        save_html_report(result, str(out))
        assert out.exists()
        content = out.read_text()
        assert "<!DOCTYPE html>" in content

    def test_save_creates_parent_dirs(self, tmp_path):
        result = _empty_result()
        nested = tmp_path / "deep" / "nested" / "report.html"
        save_html_report(result, str(nested))
        assert nested.exists()

    def test_save_with_title_kwarg(self, tmp_path):
        result = _basic_result()
        out = tmp_path / "titled.html"
        save_html_report(result, str(out), title="Custom Title")
        content = out.read_text()
        assert "Custom Title" in content


class TestSaveReport:
    def test_save_creates_file(self, tmp_path):
        result = _basic_result()
        out = str(tmp_path / "report.html")
        save_html_report(result, out, title="Save Test")
        with open(out) as f:
            content = f.read()
        assert "<!DOCTYPE html>" in content
        assert "Save Test" in content

    def test_save_creates_parent_dirs(self, tmp_path):
        result = _basic_result()
        out = str(tmp_path / "sub" / "dir" / "report.html")
        save_html_report(result, out)
        with open(out) as f:
            content = f.read()
        assert "<!DOCTYPE html>" in content


class TestSelfContained:
    def test_no_external_css_links(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert '<link rel="stylesheet"' not in report

    def test_no_external_script_src(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert 'src="http' not in report

    def test_all_css_inline(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "<style>" in report
        assert "--bg:" in report

    def test_all_js_inline(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "<script>" in report


class TestExecutiveSummary:
    def test_board_name_in_summary(self):
        result = _basic_result()
        report = generate_html_report(result, title="Alpha Board")
        assert "Alpha Board" in report

    def test_component_count_in_summary(self):
        result = _basic_result()
        report = generate_html_report(result)
        assert "3 components" in report

    def test_findings_count_in_summary(self):
        result = _security_result()
        report = generate_html_report(result)
        # Should mention severity counts
        assert "HIGH" in report


class TestResponsive:
    def test_viewport_meta(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert 'name="viewport"' in report
        assert "width=device-width" in report

    def test_responsive_media_query(self):
        result = _empty_result()
        report = generate_html_report(result)
        assert "@media (max-width: 768px)" in report
