"""JTAGulator config export — generates pin configs and OpenOCD snippets from detected debug interfaces."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from retrace.export.pinout_diagram import _PINOUTS, _best_pinout

# ---------------------------------------------------------------------------
# Voltage lookup — common interface voltages
# ---------------------------------------------------------------------------

_VOLTAGE_DEFAULTS: dict[str, str] = {
    "JTAG": "3.3",
    "SWD": "3.3",
    "UART": "3.3",
    "SPI": "3.3",
    "I2C": "3.3",
}

_UART_COMMON_BAUDS = [9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600]

# ---------------------------------------------------------------------------
# OpenOCD transport/interface templates
# ---------------------------------------------------------------------------

_OPENOCD_INTERFACE_TEMPLATE = """\
# OpenOCD configuration — auto-generated by re:trace
# Interface: {interface}
# Component: {component_ref}
# Generated: {timestamp}
#
# WARNING: Verify target voltage before connecting.
# Adjust interface/transport to match your debug probe.

# --- Interface (change to match your probe) ---
source [find interface/ftdi/generic.cfg]

# --- Transport ---
transport select {transport}

# --- Target ---
# Uncomment and adjust for your target MCU/SoC:
# source [find target/stm32f4x.cfg]
# source [find target/nrf52.cfg]
# source [find target/esp32.cfg]

# --- Adapter speed (kHz) ---
adapter speed 1000

# --- Reset config ---
reset_config srst_only srst_nogate
"""

_OPENOCD_JTAG_EXTRAS = """\
# --- JTAG-specific ---
# If scan chain has multiple TAPs, adjust:
# jtag newtap auto0 tap -irlen 4 -expected-id 0x00000000

# Scan chain verification:
# > scan_chain
"""

_OPENOCD_SWD_EXTRAS = """\
# --- SWD-specific ---
# SWD multi-drop (if multiple targets on bus):
# swd multidrop 0

# DAP configuration:
# dap create auto0.dap -chain-position auto0.tap
"""


# ---------------------------------------------------------------------------
# Pin extraction helpers
# ---------------------------------------------------------------------------

def _extract_signal_pins(
    interface: str,
    pins: list[tuple[str, str, str]],
) -> dict[str, list[dict[str, Any]]]:
    """Group pins by function for JTAGulator config output.

    Returns a dict mapping signal names to pin info dicts with keys:
    pin_number, name, group, description.
    """
    signals: dict[str, list[dict[str, Any]]] = {}
    for i, (name, group, desc) in enumerate(pins):
        pin_info = {
            "pin_number": i + 1,
            "name": name,
            "group": group,
            "description": desc,
        }
        # Normalize signal name for grouping
        base_name = name.split("/")[0].strip().upper()
        if base_name not in signals:
            signals[base_name] = []
        signals[base_name].append(pin_info)
    return signals


def _jtag_signal_pins(
    pins: list[tuple[str, str, str]],
) -> dict[str, int | None]:
    """Extract JTAG signal pin numbers from a pin list.

    Returns dict with keys TDI, TDO, TCK, TMS, TRST (pin number or None).
    """
    result: dict[str, int | None] = {
        "TDI": None, "TDO": None, "TCK": None, "TMS": None, "TRST": None,
    }
    for i, (name, _group, _desc) in enumerate(pins):
        upper = name.upper()
        for sig in result:
            if sig in upper:
                result[sig] = i + 1
                break
        # nTRST maps to TRST
        if "NTRST" in upper and result["TRST"] is None:
            result["TRST"] = i + 1
    return result


def _swd_signal_pins(
    pins: list[tuple[str, str, str]],
) -> dict[str, int | None]:
    """Extract SWD signal pin numbers."""
    result: dict[str, int | None] = {
        "SWDIO": None, "SWCLK": None, "SWO": None, "RESET": None,
    }
    for i, (name, _group, _desc) in enumerate(pins):
        upper = name.upper()
        if "SWDIO" in upper:
            result["SWDIO"] = i + 1
        elif "SWCLK" in upper or "SWCLK" in upper.replace(" ", ""):
            result["SWCLK"] = i + 1
        elif "SWO" in upper:
            result["SWO"] = i + 1
        elif "RESET" in upper or "NRST" in upper:
            result["RESET"] = i + 1
    return result


def _uart_signal_pins(
    pins: list[tuple[str, str, str]],
) -> dict[str, int | None]:
    """Extract UART signal pin numbers."""
    result: dict[str, int | None] = {"TX": None, "RX": None, "GND": None}
    for i, (name, group, _desc) in enumerate(pins):
        upper = name.upper()
        if upper in ("TX", "TX1") or (upper == "TX" and group == "data"):
            result["TX"] = i + 1
        elif upper in ("RX", "RX1") or (upper == "RX" and group == "data"):
            result["RX"] = i + 1
        elif upper == "GND" and result["GND"] is None:
            result["GND"] = i + 1
    return result


# ---------------------------------------------------------------------------
# JTAGulator config generation
# ---------------------------------------------------------------------------

def generate_jtagulator_config(
    findings: list[dict[str, Any]],
    *,
    board_name: str = "unknown",
    voltage: str | None = None,
) -> str:
    """Generate a JTAGulator-compatible pin configuration text file.

    Args:
        findings: List of debug interface finding dicts from detect_debug_interfaces().
        board_name: Human-readable board name for comments.
        voltage: Target voltage override (e.g. "3.3", "1.8", "5.0").

    Returns:
        Multi-line string with JTAGulator commands, pin mapping comments,
        and interface-specific instructions.
    """
    if not findings:
        return _no_interfaces_found(board_name)

    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    lines: list[str] = [
        "# ============================================================",
        f"# JTAGulator Configuration — {board_name}",
        f"# Generated by re:trace on {timestamp}",
        "# ============================================================",
        "#",
        "# SAFETY WARNINGS:",
        "#   1. Verify target voltage BEFORE connecting JTAGulator",
        "#   2. Set JTAGulator voltage to match target (V command)",
        "#   3. Connect GND first, then signal pins",
        "#   4. Never exceed target voltage — magic smoke is permanent",
        "#",
        "# QUICK START:",
        "#   1. Connect JTAGulator CH0-CHn to suspected debug header pins",
        "#   2. Open serial terminal to JTAGulator (115200 baud)",
        "#   3. Set target voltage: V",
        "#   4. Run the scan command for detected interface type",
        "#",
        "",
    ]

    for finding in findings:
        interface = finding.get("interface", "UNKNOWN")
        comp_label = finding.get("component_label", "")
        comp_marking = finding.get("component_marking", "")
        comp_ref = f"{comp_label} ({comp_marking})" if comp_marking else comp_label
        iface_voltage = voltage or _VOLTAGE_DEFAULTS.get(interface, "3.3")

        lines.append(f"# --- {interface} Interface ---")
        lines.append(f"# Component: {comp_ref}")
        if finding.get("cvss_base"):
            lines.append(f"# Risk: CVSS {finding['cvss_base']} — {finding.get('description', '')}")
        if finding.get("cve_reference"):
            lines.append(f"# CWE: {finding['cve_reference']}")
        lines.append(f"# Target voltage: {iface_voltage}V")
        lines.append("")

        if interface == "JTAG":
            lines.extend(_jtag_config_section(finding, iface_voltage))
        elif interface == "UART":
            lines.extend(_uart_config_section(finding, iface_voltage))
        elif interface == "SWD":
            lines.extend(_swd_config_section(finding, iface_voltage))
        elif interface == "SPI":
            lines.extend(_spi_config_section(finding, iface_voltage))
        elif interface == "I2C":
            lines.extend(_i2c_config_section(finding, iface_voltage))
        else:
            lines.append(f"# Unsupported interface: {interface}")
            lines.append("")

    lines.append("# ============================================================")
    lines.append("# End of JTAGulator configuration")
    lines.append("# ============================================================")

    return "\n".join(lines) + "\n"


def _no_interfaces_found(board_name: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        f"# JTAGulator Configuration — {board_name}\n"
        f"# Generated by re:trace on {timestamp}\n"
        "#\n"
        "# No debug interfaces detected on this board.\n"
        "# Try manual probing:\n"
        "#   - Look for unpopulated headers (2x5, 2x7, 2x10 pin)\n"
        "#   - Check for test pads near MCU/SoC\n"
        "#   - Inspect silkscreen for TDI/TDO/TCK/TMS/TX/RX labels\n"
        "#   - Use JTAGulator IDCODE scan on all accessible pins\n"
    )


def _get_pinout_for_finding(finding: dict[str, Any]) -> list[tuple[str, str, str]]:
    """Resolve the pinout list for a finding, using component data if available."""
    interface = finding.get("interface", "JTAG")
    # If the finding has pin_count info, use it; otherwise pick the largest
    iface_pins = _PINOUTS.get(interface, {})
    if not iface_pins:
        return []
    # Default to the largest pin count for the interface
    pin_count = max(iface_pins.keys())
    return _best_pinout(interface, pin_count)


def _jtag_config_section(finding: dict[str, Any], voltage: str) -> list[str]:
    pins = _get_pinout_for_finding(finding)
    sig = _jtag_signal_pins(pins)
    lines: list[str] = []

    lines.append("# Pin mapping (header pin -> signal):")
    for signal, pin_num in sig.items():
        if pin_num is not None:
            lines.append(f"#   Pin {pin_num:2d} -> {signal}")
    lines.append("")

    lines.append("# JTAGulator commands:")
    lines.append("#   V            — Set target voltage")
    lines.append(f"#                  Enter: {voltage}")
    lines.append("#   J            — JTAG IDCODE scan")
    lines.append("#                  Scans all channel combinations for JTAG devices")
    lines.append("#                  Connect header pins to CH0, CH1, CH2, ... sequentially")
    lines.append("#   B            — JTAG BYPASS scan")
    lines.append("#                  Determines number of devices in scan chain")
    lines.append("")

    lines.append("# Suggested JTAGulator channel assignment:")
    ch = 0
    for signal in ("TCK", "TMS", "TDI", "TDO", "TRST"):
        pin_num = sig.get(signal)
        if pin_num is not None:
            lines.append(f"#   CH{ch} -> Header Pin {pin_num} ({signal})")
            ch += 1
    lines.append("")

    lines.append("# After identifying JTAG pins, use OpenOCD:")
    lines.append("#   openocd -f interface/ftdi/generic.cfg -c 'transport select jtag' \\")
    lines.append("#     -c 'adapter speed 1000' -c 'init' -c 'scan_chain'")
    lines.append("")
    return lines


def _uart_config_section(finding: dict[str, Any], voltage: str) -> list[str]:
    pins = _get_pinout_for_finding(finding)
    sig = _uart_signal_pins(pins)
    lines: list[str] = []

    lines.append("# Pin mapping (header pin -> signal):")
    for signal, pin_num in sig.items():
        if pin_num is not None:
            lines.append(f"#   Pin {pin_num:2d} -> {signal}")
    lines.append("#")
    lines.append("#   NOTE: TX/RX are labeled from the TARGET's perspective.")
    lines.append("#   Connect target TX -> adapter RX, target RX -> adapter TX.")
    lines.append("")

    lines.append("# JTAGulator commands:")
    lines.append("#   V            — Set target voltage")
    lines.append(f"#                  Enter: {voltage}")
    lines.append("#   U            — UART passthrough")
    lines.append("#                  Identify TX pin, then enter passthrough mode")
    lines.append("#   P            — UART scan / baud rate detection")
    lines.append("#                  Auto-detect baud rate on suspected TX pin")
    lines.append("")

    lines.append("# Common baud rates to try:")
    for baud in _UART_COMMON_BAUDS:
        marker = " <-- most common" if baud == 115200 else ""
        lines.append(f"#   {baud:>7d}{marker}")
    lines.append("")

    lines.append("# After identifying UART pins:")
    lines.append("#   screen /dev/ttyUSB0 115200")
    lines.append("#   minicom -D /dev/ttyUSB0 -b 115200")
    lines.append("#   picocom -b 115200 /dev/ttyUSB0")
    lines.append("")
    return lines


def _swd_config_section(finding: dict[str, Any], voltage: str) -> list[str]:
    pins = _get_pinout_for_finding(finding)
    sig = _swd_signal_pins(pins)
    lines: list[str] = []

    lines.append("# Pin mapping (header pin -> signal):")
    for signal, pin_num in sig.items():
        if pin_num is not None:
            lines.append(f"#   Pin {pin_num:2d} -> {signal}")
    lines.append("")

    lines.append("# JTAGulator commands:")
    lines.append("#   V            — Set target voltage")
    lines.append(f"#                  Enter: {voltage}")
    lines.append("#   D            — SWD IDCODE scan")
    lines.append("#                  Scans channel pairs for SWD targets")
    lines.append("#                  Need only SWDIO + SWCLK + GND (3-wire)")
    lines.append("")

    lines.append("# Suggested JTAGulator channel assignment:")
    ch = 0
    for signal in ("SWCLK", "SWDIO"):
        pin_num = sig.get(signal)
        if pin_num is not None:
            lines.append(f"#   CH{ch} -> Header Pin {pin_num} ({signal})")
            ch += 1
    lines.append("")

    lines.append("# After identifying SWD pins, use OpenOCD or pyOCD:")
    lines.append("#   openocd -f interface/cmsis-dap.cfg -c 'transport select swd' \\")
    lines.append("#     -c 'adapter speed 1000' -c 'init' -c 'targets'")
    lines.append("#   pyocd commander --target auto")
    lines.append("")
    return lines


def _spi_config_section(finding: dict[str, Any], voltage: str) -> list[str]:
    lines: list[str] = []
    lines.append("# SPI is not directly supported by JTAGulator scan commands,")
    lines.append("# but you can use it for voltage-safe probing.")
    lines.append("")
    lines.append("# For SPI flash extraction, use:")
    lines.append("#   flashrom -p <programmer> -r firmware.bin")
    lines.append("#   Bus Pirate: flashrom -p buspirate_spi:dev=/dev/ttyUSB0")
    lines.append("#   FTDI: flashrom -p ft2232_spi:type=generic")
    lines.append("")
    return lines


def _i2c_config_section(finding: dict[str, Any], voltage: str) -> list[str]:
    lines: list[str] = []
    lines.append("# I2C is not directly supported by JTAGulator scan commands.")
    lines.append("")
    lines.append("# For I2C bus enumeration, use:")
    lines.append("#   i2cdetect -y 1")
    lines.append("#   Bus Pirate: set mode I2C, then (1) scan")
    lines.append("")
    return lines


# ---------------------------------------------------------------------------
# OpenOCD config generation
# ---------------------------------------------------------------------------

def generate_openocd_config(
    findings: list[dict[str, Any]],
    *,
    board_name: str = "unknown",
) -> str:
    """Generate an OpenOCD .cfg snippet for detected JTAG/SWD interfaces.

    Only JTAG and SWD interfaces produce meaningful OpenOCD configs.

    Args:
        findings: List of debug interface finding dicts.
        board_name: Board name for comments.

    Returns:
        OpenOCD config string, or empty string if no JTAG/SWD detected.
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    configs: list[str] = []

    for finding in findings:
        interface = finding.get("interface", "")
        if interface not in ("JTAG", "SWD"):
            continue

        comp_label = finding.get("component_label", "")
        comp_marking = finding.get("component_marking", "")
        comp_ref = f"{comp_label} ({comp_marking})" if comp_marking else comp_label
        transport = "jtag" if interface == "JTAG" else "swd"

        cfg = _OPENOCD_INTERFACE_TEMPLATE.format(
            interface=interface,
            component_ref=comp_ref,
            timestamp=timestamp,
            transport=transport,
        )

        if interface == "JTAG":
            cfg += _OPENOCD_JTAG_EXTRAS
        elif interface == "SWD":
            cfg += _OPENOCD_SWD_EXTRAS

        configs.append(cfg)

    return "\n".join(configs)


# ---------------------------------------------------------------------------
# Combined export (convenience for CLI)
# ---------------------------------------------------------------------------

def export_jtagulator_configs(
    findings: list[dict[str, Any]],
    *,
    board_name: str = "unknown",
    voltage: str | None = None,
) -> dict[str, str]:
    """Generate all JTAGulator-related config files.

    Returns:
        Dict mapping filename to content:
        - "jtagulator.txt": JTAGulator pin config
        - "openocd.cfg": OpenOCD config (only if JTAG/SWD detected)
    """
    result: dict[str, str] = {}

    result["jtagulator.txt"] = generate_jtagulator_config(
        findings, board_name=board_name, voltage=voltage,
    )

    openocd = generate_openocd_config(findings, board_name=board_name)
    if openocd.strip():
        result["openocd.cfg"] = openocd

    return result
